version: "3"

services:
  database:
    container_name: ${PROJECT_NAME}_database
    restart: always
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

  php-apache:
    container_name: ${PROJECT_NAME}_php-apache
    build:
      context: ./docker/php
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/laravel_docker
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
