openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
paths:
  /api/forum/topics:
    get:
      summary: 'GET topics'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    title: 'Aliquid ex ut quia eum.'
                    body: 'Или же просто восклицания: «черви! червоточина! пикенция!» или: «пикендрас! пичурущух! пичура!» и даже бузиной, подлец, затирает; но — из комнаты не было мебели, хотя и было говорено в первые — дни!.'
                    user_id: 3
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 2
                    title: 'Iste iusto incidunt quia.'
                    body: 'Как несметное множество церквей, монастырей с куполами, главами, крестами, рассыпано на святой, благочестивой Руси, так несметное множество племен, поколений, народов толпится, пестреет и мечется по.'
                    user_id: 2
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 3
                    title: 'Possimus in sed voluptatem est.'
                    body: 'Но ведь что, главное, в ней просто, она скажет, что ей вздумается, засмеется, где захочет засмеяться. Из нее все можно сделать, она может быть счастия или — так прямо направо. — Направо? — отозвался.'
                    user_id: 9
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 4
                    title: test
                    body: test
                    user_id: 1
                    created_at: '2021-08-25T12:28:00.000000Z'
                    updated_at: '2021-08-25T12:28:00.000000Z'
                  -
                    id: 5
                    title: test
                    body: test
                    user_id: 1
                    created_at: '2021-08-25T12:28:12.000000Z'
                    updated_at: '2021-08-25T12:28:12.000000Z'
                  -
                    id: 6
                    title: new
                    body: body
                    user_id: 1
                    created_at: '2021-08-26T05:21:12.000000Z'
                    updated_at: '2021-08-26T05:21:12.000000Z'
      tags:
        - Endpoints
      security: []
  '/api/forum/topic/{id}':
    get:
      summary: 'GET topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Post is not exists'
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор поста'
        example: 15
        required: true
        schema:
          type: integer
  '/api/forum/topic/{id}/comments':
    get:
      summary: 'GET topic comments'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 21
                    body: eeeeeeeeeeeeeeeeee
                    commentable_id: 6
                    commentable_type: App\Models\Topic
                    user_id: 1
                    created_at: '2021-08-26T05:25:00.000000Z'
                    updated_at: '2021-08-26T05:25:00.000000Z'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор поста'
        example: 6
        required: true
        schema:
          type: integer
  '/api/forum/topic/comment/{id}':
    delete:
      summary: 'DELETE topic comment'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор комментария'
        example: 16
        required: true
        schema:
          type: integer
  /api/forum/topic:
    post:
      summary: 'POST Add topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 'Идентификатор пользователя'
                  example: 1
                title:
                  type: string
                  description: 'Название поста.'
                  example: title
                body:
                  type: string
                  description: 'Тело поста.'
                  example: 'Status of work is...'
              required:
                - user_id
                - title
                - body
      security: []
  '/api/forum/topic/{id}/comment':
    post:
      summary: 'POST Add comment'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 'Идентификатор пользователя'
                  example: 1
                body:
                  type: string
                  description: 'Тело комментария'
                  example: 'I think...'
              required:
                - user_id
                - body
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the topic.'
        example: 2
        required: true
        schema:
          type: integer
  /api/users:
    get:
      summary: 'GET users'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: 'Selina Labadie'
                    email: szemlak@example.net
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 2
                    name: 'Prof. Kiarra Gerlach V'
                    email: beaulah90@example.net
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 3
                    name: 'Prof. Ayden Jenkins'
                    email: winston.gutmann@example.org
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 4
                    name: 'Prof. Rickey Nolan Jr.'
                    email: braden58@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 5
                    name: 'Ari Homenick'
                    email: paige15@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 6
                    name: 'Maximillian Gottlieb'
                    email: marilie.botsford@example.org
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 7
                    name: 'Ms. Aliya Bradtke DVM'
                    email: myah19@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 8
                    name: 'Reina Reichert'
                    email: jean42@example.org
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 9
                    name: 'Corine Smitham'
                    email: zprice@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 10
                    name: 'Mr. Caden Walter PhD'
                    email: jennings.mcglynn@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 11
                    name: 'Sasha Jast'
                    email: hansen.ocie@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 12
                    name: 'Rigoberto Koss'
                    email: treutel.carol@example.org
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 13
                    name: 'Rowland Hermann'
                    email: kian.emard@example.com
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 14
                    name: 'King Huel DVM'
                    email: cruz.block@example.net
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
                  -
                    id: 15
                    name: 'Pearlie Christiansen'
                    email: hamill.ricardo@example.net
                    email_verified_at: '2021-08-23T14:44:54.000000Z'
                    created_at: '2021-08-23T14:44:54.000000Z'
                    updated_at: '2021-08-23T14:44:54.000000Z'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
