openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
paths:
  /api/users:
    get:
      summary: 'GET users'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: 'Mitchell Goodwin'
                    email: janae11@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 2
                    name: 'Prof. Raleigh O''Kon'
                    email: rylee.krajcik@example.com
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 3
                    name: 'Karianne Hoppe'
                    email: kendra69@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 4
                    name: 'Keenan Cronin II'
                    email: chaz.kohler@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 5
                    name: 'Felipe Schuster II'
                    email: ucrona@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 6
                    name: 'Miss Ellen Zulauf'
                    email: hessel.lemuel@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 7
                    name: 'Margot Runolfsson MD'
                    email: dorian84@example.com
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 8
                    name: 'Ms. Maeve Morar'
                    email: weissnat.berta@example.net
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 9
                    name: 'Lavon Cronin'
                    email: maximilian.torphy@example.com
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 10
                    name: 'Miss Miracle Rempel PhD'
                    email: bogan.erick@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 11
                    name: 'Clovis Romaguera'
                    email: ebert.krista@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 12
                    name: 'Miss Gabriella Bartell III'
                    email: sipes.susana@example.net
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 13
                    name: 'Mr. Raheem Wolff'
                    email: sterling99@example.net
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 14
                    name: 'Mr. Russ Kozey IV'
                    email: mattie.west@example.net
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 15
                    name: 'Gudrun Hudson'
                    email: kelli51@example.org
                    email_verified_at: '2021-08-26T12:20:21.000000Z'
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
      tags:
        - Endpoints
      security: []
  /api/forum/topics:
    get:
      summary: 'GET topics'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    title: 'Architecto est doloribus omnis quaerat et.'
                    body: 'Глава третья А Чичиков от нечего делать занялся, находясь позади рассматриваньем всего просторного его оклада. Как взглянул он на постель, она опустилась под ним кренделем, заснул в ту же минуту.'
                    user_id: 2
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 2
                    title: 'Non enim veritatis placeat.'
                    body: 'Чичиков узнал Ноздрева, того самого, с которым бы в ход и жил бы ты без ружья, как без шапки. Эх, брат Чичиков, то есть что Петрушка ходил в несколько минут перед дверями гостиной, взаимно упрашивая.'
                    user_id: 5
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
                  -
                    id: 3
                    title: 'Nesciunt porro porro ut tenetur hic maxime.'
                    body: 'Да вот теперь у тебя за жидовское побуждение. Ты бы должен — просто квас. Вообрази, не клико, а какое-то клико-матрадура, это — такая бестия, подсел к ней скорее! — Да, хорошая будет собака. — А на.'
                    user_id: 9
                    created_at: '2021-08-26T12:20:21.000000Z'
                    updated_at: '2021-08-26T12:20:21.000000Z'
      tags:
        - Endpoints
      security: []
  '/api/forum/topic/{id}':
    get:
      summary: 'GET topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Post is not exists'
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'DELETE topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор поста'
        example: 20
        required: true
        schema:
          type: integer
  '/api/forum/topic/{id}/comments':
    get:
      summary: 'GET topic comments'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Post is not exists'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор поста'
        example: 4
        required: true
        schema:
          type: integer
  '/api/forum/topic/comment/{id}':
    delete:
      summary: 'DELETE topic comment'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'Идентификатор комментария'
        example: 9
        required: true
        schema:
          type: integer
  /api/forum/topic:
    post:
      summary: 'POST Add topic'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 'Идентификатор пользователя'
                  example: 1
                title:
                  type: string
                  description: 'Название поста.'
                  example: title
                body:
                  type: string
                  description: 'Тело поста.'
                  example: 'Status of work is...'
              required:
                - user_id
                - title
                - body
      security: []
  '/api/forum/topic/{id}/comment':
    post:
      summary: 'POST Add comment'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 'Идентификатор пользователя'
                  example: 1
                body:
                  type: string
                  description: 'Тело комментария'
                  example: 'I think...'
              required:
                - user_id
                - body
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the topic.'
        example: 10
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
